# -*- coding: utf-8 -*-
"""Advanced Data Visualization with Matplotlib and Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19eoAvIbyA61MfMPr5_0-Zc_akECZYsqw
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Create a sample DataFrame
data = pd.DataFrame({
    'x': np.linspace(0, 10, 100),
    'y': np.sin(np.linspace(0, 10, 100)) + np.random.normal(0, 0.1, 100)
})

# Plotting
plt.scatter(data['x'], data['y'], label='Data Points')
plt.plot(data['x'], data['y'].rolling(5).mean(), color='red', label='Rolling Mean')
plt.title('Advanced Data Visualization')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.legend()
plt.show()

