# -*- coding: utf-8 -*-
"""Statistical Analysis (Matrix Exponentiation).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gtFFMuR_IaT-KKZ9AxuP66gSJhLnBIFB
"""

import numpy as np

# Define a square matrix
matrix = np.array([[5, 0], [0, 5]])

# Perform matrix exponentiation
exponentiated_matrix = np.linalg.matrix_power(matrix, 3)

print("Original Matrix:\n", matrix)
print("Matrix Exponentiation (Power 3):\n", exponentiated_matrix)

