# -*- coding: utf-8 -*-
"""Multiple Y-Axes Sharing a Common X-Axis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P4Vv11xjSRLkV0IPDGBoR_CV1oNeCIUQ
"""

import matplotlib.pyplot as plt
import numpy as np

# Sample data
x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)

fig, ax1 = plt.subplots()

# First y-axis
ax1.plot(x, y1, 'g-', label='sin(x)')
ax1.set_xlabel('X-axis')
ax1.set_ylabel('sin(x)', color='g')
ax1.tick_params(axis='y', labelcolor='g')

# Second y-axis
ax2 = ax1.twinx()
ax2.plot(x, y2, 'b-', label='cos(x)')
ax2.set_ylabel('cos(x)', color='b')
ax2.tick_params(axis='y', labelcolor='b')

fig.tight_layout()
plt.title('Multiple Y-Axes Sharing a Common X-Axis')
plt.show()

